services:
  checkpoint-kenny:
    container_name: checkpoint-kenny
    build: 
      context: .
    env_file: 
      - ../.env
    depends_on:
      - postgres
      - nats
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kenny.rule=Host(`homelab.fault.local`)" #TODO: define name in dns
      - "traefik.http.routers.kenny.entrypoints=web"
      - "traefik.http.services.kenny.loadbalancer.server.port=3000" # Kenny's internal port

    
    # Security Sandboxing
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # Rust apps occasionally need to write temporary files (e.g., during network requests)
    tmpfs:
      - /tmp
