services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true" # Enables the web UI dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Do not expose DBs/NATS by accident
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Dashboard port
    volumes:
      - "${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:ro,z"
    restart: unless-stopped
